### PR TITLE
Multiple-bit-flips-in-multiple-words

### PR DESCRIPTION
**Pull request by Behroosh**
This pull request consists of the changes I made to LLFI to facilitate the injection of multiple bit-flip errors into multiple words. I also added two sample yaml files and a sample program.

### CODE REVIEW

**Comment by abrahamchan** [comment]
I have successfully built and executed the regression test suite on this pull request.

**Comment by abrahamchan** [comment]
I will proceed to merge this PR as I don't spot any issues in the commits.

**Comment by Behroosh** [comment]
Thanks Abraham for taking care of this.
I will also now update the bin/input_masterlist.yaml file with new runtime options.

**Comment by abrahamchan** [comment]
@Behroosh Thanks for contributing back to LLFI.

**Pull request merged**
